# Site settings
title: Sanjay Korde
name: Sanjay Korde

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/sanjaykorde

 - title: LinkedIn
   url: https://www.linkedin.com/in/sanjay-korde-429a8b3b/

#Any buzzword skills you want to include
skills:
 - BMC Control-M Workload Automation
 - Microservices
 - Amazon Web Services
 - Google Cloud
 - Python
 - Java
 - SQL
 - Technical Architecture
 - Machine learning


#Work experience is required
roles:
 - title: Senior Software Engineer
   start: 2017
   end: Ongoing
   employer: HSBC Software Development India
   description: Control-M Workload Automation
 - title: Senior Systems Engineer
   start: 2015
   end: 2016
   employer: Cognizant Technology Solutions
   description: Control-M Workload Automation
 - title: Software Developer
   start: 2013
   end: 2015
   employer: Syntel Limited
   description: Mainframe Developer

#Education is required
education:
 - level: Bachelor of Engineering (B.E.)
   date: 2012
   subject: Electronics and Communications Engineering
   school: University of Birmingham



intro: Currently associated with HSBC Bank's Infrastructure Delivery team.xperience in working on projects involving IT Infrastructure (Production Control & Scheduling) Application Library Management, Software Development, Maintenance, Enhancement and Production Support.<br />
Experienced in co-ordination and assisting different application teams in planning work activities, installation, configuration and maintenance. Involved in migration of control-m to new version and coordination with different regional Data-centers for migrations/Off shoring of Projects and done outstanding transition work.<br>
Having strong technical skills in Production Control & Batch Scheduling and maintenance that include Banking, Insurance and Healthcare as domain.  Have delivered control-m trainings to corporate teams on the BMC Workload Automation 9.0 and many other tools like Zeke/Zebb

theme: jekyll-theme-cayman
